"""
Demo: Document Loading with LlamaIndex
Loading documents correctly with Tunisian-focused examples
"""

import os
import sys
from pathlib import Path
from llama_index.core import Document, SimpleDirectoryReader

# Setup paths
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

# Documents live here — created separately, not generated by this script
docs_dir = project_root / "sample_documents"


def example_1_basic_loading():
    """Example 1: Basic document loading"""
    print("\n" + "="*60)
    print("Example 1: Loading Tunisian Documents with SimpleDirectoryReader")
    print("="*60)

    # SimpleDirectoryReader scans the folder and creates one Document per file.
    # It auto-detects file type (txt, pdf, docx…) and fills in metadata
    # like file_name, file_path, creation_date without any extra config.
    reader = SimpleDirectoryReader(input_dir=str(docs_dir))
    documents = reader.load_data()

    print(f"\n✓ Loaded {len(documents)} Tunisian documents")

    for i, doc in enumerate(documents, 1):
        text_preview = doc.text[:100] + "..." if len(doc.text) > 100 else doc.text
        print(f"\nDocument #{i}:")
        print(f"  - Character count: {len(doc.text)}")
        print(f"  - Content: {text_preview}")
        # metadata is a plain dict — we can add/filter by any key later in retrieval
        print(f"  - Metadata: {doc.metadata}")


def example_2_custom_metadata():
    """Example 2: Add custom metadata"""
    print("\n" + "="*60)
    print("Example 2: Adding Custom Metadata to Documents")
    print("="*60)

    reader = SimpleDirectoryReader(input_dir=str(docs_dir))
    documents = reader.load_data()

    # Metadata travels with the document through the whole RAG pipeline.
    # Adding a "category" key here means we can later filter searches to
    # only look inside History docs, or only Food docs — without re-indexing.
    categories = {
        "tunisian_history.txt": "History",
        "tunisian_cuisine.txt": "Food",
        "tunisian_culture.txt": "Culture"
    }

    for doc in documents:
        filename = doc.metadata.get("file_name", "")
        if filename in categories:
            doc.metadata["category"] = categories[filename]
            doc.metadata["language"] = "English"
            doc.metadata["region"] = "Tunisia"
            doc.metadata["culture"] = "North Africa"

    print("\n✓ Added custom metadata:")
    for doc in documents:
        print(f"\nFile: {doc.metadata.get('file_name')}")
        print(f"  Category: {doc.metadata.get('category')}")
        print(f"  Language: {doc.metadata.get('language')}")
        print(f"  Region: {doc.metadata.get('region')}")


def example_3_manual_documents():
    """Example 3: Create documents manually"""
    print("\n" + "="*60)
    print("Example 3: Creating Documents Manually")
    print("="*60)

    # Use Document() directly when text comes from a database, API, or user input
    # rather than from files on disk. The structure is identical — LlamaIndex
    # treats it the same way during chunking and indexing.
    documents = [
        Document(
            text="The cat sat on the mat and looked out the window.",
            metadata={"title": "Cat Story", "category": "animal", "length": "short"}
        ),
        Document(
            text="A red apple fell from the tree into the garden.",
            metadata={"title": "Apple", "category": "nature", "length": "short"}
        ),
        Document(
            text="The old bicycle leaned against the wall near the door.",
            metadata={"title": "Bicycle", "category": "object", "length": "short"}
        ),
        Document(
            text="Rain started falling slowly on the empty street.",
            metadata={"title": "Rainy Street", "category": "weather", "length": "short"}
        ),
    ]

    print(f"\n✓ Created {len(documents)} documents manually")

    for doc in documents:
        print(f"\n- Title: {doc.metadata.get('title')}")
        print(f"  Category: {doc.metadata.get('category')}")
        print(f"  Length: {doc.metadata.get('length')}")
        print(f"  Text: {doc.text}")


def example_4_document_stats():
    """Example 4: Statistics about documents"""
    print("\n" + "="*60)
    print("Example 4: Statistics About Loaded Tunisian Documents")
    print("="*60)

    reader = SimpleDirectoryReader(input_dir=str(docs_dir))
    documents = reader.load_data()

    # These stats matter when choosing chunk_size later.
    # If average doc size is 1000 chars and we chunk at 512 tokens,
    # each document will produce roughly 2 chunks — a useful baseline.
    total_chars = sum(len(doc.text) for doc in documents)
    total_words = sum(len(doc.text.split()) for doc in documents)
    avg_doc_size = total_chars / len(documents) if documents else 0

    print(f"\n📊 Statistics:")
    print(f"  - Number of documents: {len(documents)}")
    print(f"  - Total characters: {total_chars}")
    print(f"  - Total words: {total_words}")
    print(f"  - Average document size: {avg_doc_size:.0f} characters")
    print(f"  - Largest document: {max(len(doc.text) for doc in documents)} characters")
    print(f"  - Smallest document: {min(len(doc.text) for doc in documents)} characters")


def main():
    """Run all examples"""
    print("\n🚀 Demo: Document Loading - Tunisian Edition")
    print("="*60)

    try:
        example_1_basic_loading()
        example_2_custom_metadata()
        example_3_manual_documents()
        example_4_document_stats()

        print("\n" + "="*60)
        print("✅ All examples completed successfully!")
        print("="*60)

    except Exception as e:
        print(f"\n❌ Error occurred: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
